name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # ตรวจสอบและแก้ไขให้ตรงกับชื่อ branch หลักของคุณ (โดยทั่วไปคือ main หรือ master)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORTORGUN }}' # แทนที่ TORTORGUN ด้วยชื่อโปรเจค Firebase ของคุณที่เป็นตัวพิมพ์ใหญ่ทั้งหมด
          channelId: live
          projectId: tortorgun # แทนที่ tortorgun ด้วย ID โปรเจค Firebase ของคุณ
